In [28]:
import pandas as pd
df = pd.read_csv('Life Expectancy Data.csv')
pd.set_option('display.max_columns',500)
df.tail(10)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2928,Zimbabwe,2009,Developing,50.0,587.0,30,4.64,1.040021,73.0,853,29.0,45,69.0,6.26,73.0,18.1,65.824121,1381599.0,7.5,7.4,0.419,9.9
2929,Zimbabwe,2008,Developing,48.2,632.0,30,3.56,20.843429,75.0,0,28.6,46,75.0,4.96,75.0,20.5,325.678573,13558469.0,7.8,7.8,0.421,9.7
2930,Zimbabwe,2007,Developing,46.6,67.0,29,3.88,29.814566,72.0,242,28.2,46,73.0,4.47,73.0,23.7,396.998217,1332999.0,8.2,8.2,0.414,9.6
2931,Zimbabwe,2006,Developing,45.4,7.0,28,4.57,34.262169,68.0,212,27.9,45,71.0,5.12,7.0,26.8,414.796232,13124267.0,8.6,8.6,0.408,9.5
2932,Zimbabwe,2005,Developing,44.6,717.0,28,4.14,8.717409,65.0,420,27.5,43,69.0,6.44,68.0,30.3,444.765750,129432.0,9.0,9.0,0.406,9.3
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,27.1,42,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,26.7,41,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,26.3,40,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,25.9,39,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,25.5,39,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [5]:
df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

In [6]:
df.index

RangeIndex(start=0, stop=2938, step=1)

In [7]:
df.info

<bound method DataFrame.info of           Country  Year      Status  Life expectancy   Adult Mortality  \
0     Afghanistan  2015  Developing              65.0            263.0
1     Afghanistan  2014  Developing              59.9            271.0
2     Afghanistan  2013  Developing              59.9            268.0
3     Afghanistan  2012  Developing              59.5            272.0
4     Afghanistan  2011  Developing              59.2            275.0
...           ...   ...         ...               ...              ...
2933     Zimbabwe  2004  Developing              44.3            723.0
2934     Zimbabwe  2003  Developing              44.5            715.0
2935     Zimbabwe  2002  Developing              44.8             73.0
2936     Zimbabwe  2001  Developing              45.3            686.0
2937     Zimbabwe  2000  Developing              46.0            665.0

      infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
0                62     0.01               71.279624         65.0      1154
1                64     0.01               73.523582         62.0       492
2                66     0.01               73.219243         64.0       430
3                69     0.01               78.184215         67.0      2787
4                71     0.01                7.097109         68.0      3013
...             ...      ...                     ...          ...       ...
2933             27     4.36                0.000000         68.0        31
2934             26     4.06                0.000000          7.0       998
2935             25     4.43                0.000000         73.0       304
2936             25     1.72                0.000000         76.0       529
2937             24     1.68                0.000000         79.0      1483

       BMI   under-five deaths   Polio  Total expenditure  Diphtheria   \
0      19.1                  83    6.0               8.16         65.0
1      18.6                  86   58.0               8.18         62.0
2      18.1                  89   62.0               8.13         64.0
3      17.6                  93   67.0               8.52         67.0
4      17.2                  97   68.0               7.87         68.0
...     ...                 ...    ...                ...          ...
2933   27.1                  42   67.0               7.13         65.0
2934   26.7                  41    7.0               6.52         68.0
2935   26.3                  40   73.0               6.53         71.0
2936   25.9                  39   76.0               6.16         75.0
2937   25.5                  39   78.0               7.10         78.0

       HIV/AIDS         GDP  Population   thinness  1-19 years  \
0           0.1  584.259210  33736494.0                   17.2
1           0.1  612.696514    327582.0                   17.5
2           0.1  631.744976  31731688.0                   17.7
3           0.1  669.959000   3696958.0                   17.9
4           0.1   63.537231   2978599.0                   18.2
...         ...         ...         ...                    ...
2933       33.6  454.366654  12777511.0                    9.4
2934       36.7  453.351155  12633897.0                    9.8
2935       39.8   57.348340    125525.0                    1.2
2936       42.1  548.587312  12366165.0                    1.6
2937       43.5  547.358878  12222251.0                   11.0

       thinness 5-9 years  Income composition of resources  Schooling
0                    17.3                            0.479       10.1
1                    17.5                            0.476       10.0
2                    17.7                            0.470        9.9
3                    18.0                            0.463        9.8
4                    18.2                            0.454        9.5
...                   ...                              ...        ...
2933                  9.4                            0.407        9.2
2934                  9.9                            0.418        9.5
2935                  1.3                            0.427       10.0
2936                  1.7                            0.427        9.8
2937                 11.2                            0.434        9.8

[2938 rows x 22 columns]>

In [8]:
df.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [9]:
df.shape
len(df)

2938

In [ ]:
df[['Life expectancy ','Alcohol']]

      Life expectancy   Alcohol
0                 65.0     0.01
1                 59.9     0.01
2                 59.9     0.01
3                 59.5     0.01
4                 59.2     0.01
...                ...      ...
2933              44.3     4.36
2934              44.5     4.06
2935              44.8     4.43
2936              45.3     1.72
2937              46.0     1.68

[2938 rows x 2 columns]